# Generated by Django 6.0.2 on 2026-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minilibrary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(related_name="books", to="minilibrary.genre"),
        ),
    ]
